udistrital/inscripcion_crud

.gitignore, controllers/enfasis_proyecto.go, controllers/grupo_investigacion.go, models/enfasis_proyecto.go, models/grupo_investigacion.go, models/propuesta.go, routers/commentsRouter_controllers.go, routers/router.go, swagger/swagger.json, swagger/swagger.yml
se añaden la gestion de los grupos de investigacion, adicionalmente el enfasis del proyecto en el cual es un enfasis diferente al enfasis del posgrado que elige el aspirante por ello se añade, para evitar confundir dichos valores.
- `grupos de ingestigacion` y `enfasis proyecto` han sido planteadas como parametricas
- se modifica el archivo `models/propuesta`
- para su correcto funcionamento es necesario ejecutar un script para realizar los cambios en la base de datos
=> adicion de gruos de investigacion y edicion del modelo de propuesta

database/migrations/20200210_135821_insert_estados_inscripcion_admision.go, database/scripts/20200210_135821_insert_estados_inscripcion_admision.down.sql, database/scripts/20200210_135821_insert_estados_inscripcion_admision.up.sql
Ajustes necesarios para el proceso de admisión con unico criterio ICFES
=> Proceso de admisión

.drone.yml
docs: Se ajusta Pipeline con nuevos lineamientos rama release
=> docs: Se ajusta Pipeline con nuevos lineamientos rama release

controllers/estado_inscripcion.go, controllers/inscripcion.go, controllers/inscripcion_posgrado.go, controllers/inscripcion_pregrado.go, controllers/propuesta.go, controllers/reintegro.go, controllers/tipo_icfes.go, controllers/tipo_inscripcion.go, controllers/tipo_proyecto.go, controllers/tr_inscripcion.go, controllers/transferencia.go, models/estado_inscripcion.go, models/inscripcion.go, models/inscripcion_posgrado.go, models/inscripcion_pregrado.go, models/propuesta.go, models/reintegro.go, models/tipo_icfes.go, models/tipo_inscripcion.go, models/tipo_proyecto.go, models/transferencia.go
_ aplicacion de libreria time_bogota en controladores
=> Se corrigen campos de fechas en modelos

models/documento_programa.go, models/soporte_documento_programa.go, models/tipo_documento_programa.go
fix: Se agrega función relatedSel en controladores nuevos de acuerdo a lineamiento. udistrital/sga_cliente#390
=> fix: Se agrega funcion relatedSel

database/migrations/20210120_152128_cambiar_tipo_dato_recibo_inscripcion.go, database/scripts/20210120_152128_cambiar_tipo_dato_recibo_inscripcion.down.sql, database/scripts/20210120_152128_cambiar_tipo_dato_recibo_inscripcion.up.sql, models/inscripcion.go, swagger/swagger.json, swagger/swagger.yml
fix: ajuste de variable recibo_inscripcion_id
=> fix: ajuste de variable recibo_inscripcion_id

models/inscripcion.go
fix: ajuste del modelo de isncripcion con los nuevos cambios
=> fix: ajuste del modelo de isncripcion con los nuevos cambios

database/migrations/20210122_071003_insert_tipo_proyecto.go, database/scripts/220210122_071003_insert_tipo_proyecto.down.sql, database/scripts/220210122_071003_insert_tipo_proyecto.up.sql, swagger/swagger.yml
fix: insert registros en tabla tipo_proyecto
=> fix: insert registros en tabla tipo_proyecto

database/migrations/20210122_071003_insert_tipo_proyecto.go, database/scripts/220210122_071003_insert_tipo_proyecto.down.sql, database/scripts/220210122_071003_insert_tipo_proyecto.up.sql, models/inscripcion.go, swagger/swagger.yml
develop : insert de modalidades de trabajo
=> develop : insert de modalidades de trabajo

database/migrations/20210128_071819_insert_estado_inscripcion.go, database/scripts/20210128_071819_insert_estado_inscripcion.down.sql, database/scripts/20210128_071819_insert_estado_inscripcion.up.sql
fix: insert estado inscripcion INSCRITO
=> fix: insert estado inscripcion INSCRITO

controllers/propuesta.go, database/migrations/20210128_071819_insert_estado_inscripcion.go, database/scripts/20210128_071819_insert_estado_inscripcion.down.sql, database/scripts/20210128_071819_insert_estado_inscripcion.up.sql
develop: insert estado inscripcion INSCRITO
=> develop: insert estado inscripcion INSCRITO

controllers/inscripcion.go
fix: ajuste formato fecha put inscripcion
=> fix: ajuste formato fecha put inscripcion

models/reintegro.go
feat: ajuste en modelo de reintegro. udistrital/sga_cliente#860
=> feat: ajuste en modelo de reintegro. udistrital/sga_cliente#860

database/scripts/20220301_194850_ajuste_tabla_reintegro.up.sql, models/reintegro.go
hotfix: ajuste en modelo de reintegro. udistrital/sga_cliente#860
=> hotfix: ajuste en modelo de reintegro. udistrital/sga_cliente#860

database/migrations/20230417_215628_add_estado_inscripcion.go, database/scripts/20230417_215628_add_estado_inscripcion.down.sql, database/scripts/20230417_215628_add_estado_inscripcion.up.sql
- https://github.com/udistrital/sga_cliente/issues/1214
=> feature: udistrital/sga_cliente#1214 add estado_inscripcion_con_observacion

.drone.yml
Update Golang from 1.14 -> 1.15 because of `lib/pq` update
Issue presented related here: https://github.com/lib/pq/issues/1121
=> fix: update golang version

.drone.yml
hotfix: go15 in update_aws_esc
=> hotfix: go15 in update_aws_esc

.drone.yml, controllers/documento_programa.go, controllers/estado_inscripcion.go, controllers/inscripcion.go, controllers/inscripcion_posgrado.go, controllers/inscripcion_pregrado.go, controllers/propuesta.go, controllers/reintegro.go, controllers/soporte_documento_programa.go, controllers/tipo_documento_programa.go, controllers/tipo_icfes.go, controllers/tipo_inscripcion.go, controllers/tipo_proyecto.go, controllers/transferencia.go
- https://github.com/udistrital/sga_cliente/issues/1257
=> fix: udistrital/sga_cliente#1257 evitar cambiar FechaCreacion

.drone.yml, controllers/documento_programa.go, controllers/estado_inscripcion.go, controllers/inscripcion.go, controllers/inscripcion_posgrado.go, controllers/inscripcion_pregrado.go, controllers/propuesta.go, controllers/reintegro.go, controllers/soporte_documento_programa.go, controllers/tipo_documento_programa.go, controllers/tipo_icfes.go, controllers/tipo_inscripcion.go, controllers/tipo_proyecto.go, controllers/transferencia.go
management: udistrital/sga_cliente#1257 evitar cambiar FechaCreacion
=> management: udistrital/sga_cliente#1257 evitar cambiar FechaCreacion

models/inscripcion.go
=> feat: add param__in:value1|value2 testing

controllers/inscripcion_evolucion_estado.go, database/migrations/20240618_000655_crear_tabla_inscripcion_evolucion_estado.go, database/scripts/20240618_000655_crear_tabla_inscripcion_evolucion_estado.down.sql, database/scripts/20240618_000655_crear_tabla_inscripcion_evolucion_estado.up.sql, models/inscripcion_evolucion_estado.go, routers/commentsRouter_controllers.go, routers/router.go, swagger/swagger.json, swagger/swagger.yml
udistrital/sga_documentacion/301
=> feat: Crear tabla inscripcion_evolucion_estado

database/migrations/20240608_082045_creacion_columna_opcion_inscripcion.go, models/inscripcion.go
https://github.com/udistrital/sga_documentacion/issues/280
=> feat: udistrital/sga_documentacion#280 Adición de la columna opción a la tabla inscripción

database/migrations/20240625_235452_crear_tabla_cupo_inscripcion.go, database/scripts/20240625_235452_crear_tabla_cupo_inscripcion.down.sql, database/scripts/20240625_235452_crear_tabla_cupo_inscripcion.up.sql
https://github.com/udistrital/sga_documentacion/issues/327
=> feat: udistrital/sga_documentacion#327 creación de las migraciones de las tablas cupo_inscripcion y documento_cupo

database/migrations/20240822_080134_creacion_columna_cupos_disponibles.go, models/cupos_inscripcion.go
https://github.com/udistrital/sga_documentacion/issues/433
=> feat: udistrital/sga_documentacion#433 Adición de columna cupos disponibles

database/migrations/20240918_080616_creacion_columna_uid.go, models/inscripcion_pregrado.go
https://github.com/udistrital/sga_documentacion/issues/485
=> feat: udistrital/sga_documentacion#485 Adición de columna de id documento en tabla de inscripción pregrado

database/migrations/20241001_161909_add_activo_to_soporte_documento_programa.go, models/soporte_documento_programa.go, swagger/swagger.json, swagger/swagger.yml
- Los campos existentes automaticamente toman un valor de `activo: true`.
---
udistrital/sga_documentacion#509
=> feat: agregar columna activo a la tabla soporte_documento_programa.

database/migrations/20241001_161909_add_activo_to_soporte_documento_programa.go, models/inscripcion.go, models/soporte_documento_programa.go, swagger/swagger.json, swagger/swagger.yml
management: agregar columna activo a la tabla soporte_documento_programa.
=> management: agregar columna activo a la tabla soporte_documento_programa.
